#!/bin/bash

echo "🔧 Appwrite Platform Configuration Fix"
echo "======================================"
echo ""
echo "❌ ISSUE: Your main Vercel domain is not configured in Appwrite"
echo ""
echo "📋 TO FIX:"
echo "1. Go to: https://cloud.appwrite.io/console/project-orderchha-app"
echo "2. Navigate to: Settings → Platforms"
echo "3. Click: 'Add Platform' → 'Web'"
echo "4. Enter:"
echo "   - Name: Production Vercel"
echo "   - Hostname: orderchha.vercel.app"
echo "   - ✅ Mark as trusted"
echo "5. Click 'Next' and then 'Create'"
echo ""
echo "🔄 Current configured domains (check these):"
echo "- orderchha-cremior3b-omthakurs-projects-a4f231e9.vercel.app (working preview)"
echo "- orderchha.vercel.app (main - needs to be added)"
echo ""
echo "💡 After adding the domain, your main URL will work immediately!"
echo "   No need to redeploy - it's a server-side configuration change."
