#!/bin/bash

echo "🚀 Mobile Footer Quick Test"
echo "=========================="
echo ""
echo "📱 Your app is running at: http://localhost:3000"
echo ""
echo "🔧 Quick Setup Steps:"
echo "1. Open: http://localhost:3000/demo"
echo "2. Click 'Enable Demo Mode' button"
echo "3. Open browser DevTools (F12)"
echo "4. Toggle device toolbar (Ctrl+Shift+M)"
echo "5. Select mobile device or set width < 768px"
echo "6. Navigate to http://localhost:3000"
echo "7. Check footer at bottom and test clicks!"
echo ""
echo "🎯 Test these URLs in mobile view:"
echo "   • http://localhost:3000 (Tables)"
echo "   • http://localhost:3000/profile (Profile)"
echo "   • http://localhost:3000/dashboard (Dashboard)"
echo "   • http://localhost:3000/settings (Settings)"
echo ""
echo "✅ Mobile footer should appear with navigation items"
echo "✅ Clicking items should navigate to different pages"
echo ""
