name: Firebase Action Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_FIREBASE_CONFIG=${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}" > .env.local
      
      - name: Build Next.js app
        env:
          NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}
        run: npm run build
        
      - name: Enable Firebase Web Frameworks
        run: npx firebase-tools@13.0.2 experiments:enable webframeworks
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
